CREATE TABLE PRODUCT (
      ID BIGINT AUTO_INCREMENT PRIMARY KEY,
      DESCRIPTION VARCHAR(2000) NOT NULL,
      IN_STOCK BIGINT NOT NULL,
      NAME VARCHAR(44) NOT NULL
      PRICE INT NOT NULL
);